import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions, getAzureToken } from "@/lib/auth";
import { fetchAllDashboardData } from "@/lib/azure";

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    const token = getAzureToken(session);

    const body = await request.json();
    const { subscriptionIds, type } = body;

    if (!subscriptionIds?.length) {
      return NextResponse.json({ error: "subscriptionIds required" }, { status: 400 });
    }

    // Fetch data for each subscription
    const allData = await Promise.all(
      subscriptionIds.map((subId: string) =>
        fetchAllDashboardData(token, subId).then((data) => ({
          subscriptionId: subId,
          ...data,
        }))
      )
    );

    // Generate a simple text-based report (PDF generation with @react-pdf/renderer
    // would be done client-side or with a more complex server setup)
    const report = generateTextReport(allData, type || "executive_overview");

    return new NextResponse(report, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="control-tower-report-${new Date().toISOString().split("T")[0]}.txt"`,
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Report generation failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

function generateTextReport(
  data: Record<string, unknown>[],
  type: string
): string {
  const now = new Date().toISOString();
  const lines: string[] = [
    "═══════════════════════════════════════════════════════════════",
    "           AZURE DEVOPS CONTROL TOWER - REPORT",
    "═══════════════════════════════════════════════════════════════",
    "",
    `Report Type: ${type.replace(/_/g, " ").toUpperCase()}`,
    `Generated: ${now}`,
    `Subscriptions: ${data.length}`,
    "",
    "───────────────────────────────────────────────────────────────",
  ];

  for (const sub of data) {
    const subId = (sub as Record<string, unknown>).subscriptionId as string;
    lines.push(`\nSubscription: ${subId}`);
    lines.push("─".repeat(60));

    for (const [key, value] of Object.entries(sub)) {
      if (key === "subscriptionId") continue;
      const result = value as { status: string; data?: unknown; error?: string };
      if (result.status === "success") {
        lines.push(`  ${key}: OK`);
        if (Array.isArray(result.data)) {
          lines.push(`    Count: ${result.data.length}`);
        }
      } else {
        lines.push(`  ${key}: ERROR - ${result.error}`);
      }
    }
  }

  lines.push("");
  lines.push("═══════════════════════════════════════════════════════════════");
  lines.push("This report was generated by Azure DevOps Control Tower.");
  lines.push("All data sourced from live Azure Management APIs.");
  lines.push("═══════════════════════════════════════════════════════════════");

  return lines.join("\n");
}
